include: package:lints/recommended.yaml

linter:
  exclude:
    - doc/**
  rules:
    - always_use_package_imports
    - avoid_print
    - curly_braces_in_flow_control_structures
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
